export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GROUP_ADD_SUCCESS = "GROUP_ADD_SUCCESS";
export const GROUP_ADD_FAILURE = "GROUP_ADD_FAILURE";
export const GROUP_GET_SUCCESS = "GROUP_GET_SUCCESS";
export const GROUP_GET_FAILURE = "GROUP_GET_FAILURE";
export const ADD_EXP_SUCCESS = "ADD_EXP_SUCCESS";
export const ADD_EXP_FAILURE = "ADD_EXP_FAILURE";